-- Run this in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  caption text not null default '',
  video_path text not null,
  video_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,video_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.videos enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;
alter table public.reports enable row level security;

create policy "profiles readable" on public.profiles for select using (true);
create policy "own profile insert" on public.profiles for insert with check (auth.uid()=id);
create policy "own profile update" on public.profiles for update using (auth.uid()=id);

create policy "videos readable" on public.videos for select using (true);
create policy "own video insert" on public.videos for insert with check (auth.uid()=user_id);
create policy "own video delete" on public.videos for delete using (auth.uid()=user_id);

create policy "likes readable" on public.likes for select using (true);
create policy "own like insert" on public.likes for insert with check (auth.uid()=user_id);
create policy "own like delete" on public.likes for delete using (auth.uid()=user_id);

create policy "comments readable" on public.comments for select using (true);
create policy "comment insert" on public.comments for insert with check (auth.uid()=user_id);
create policy "own comment delete" on public.comments for delete using (auth.uid()=user_id);

create policy "reports insert" on public.reports for insert with check (auth.uid()=reporter_id);
-- Reports should not be publicly readable; moderation can use a protected admin workflow.

-- Create a Storage bucket named "videos" in the Supabase Dashboard.
-- Then add Storage policies so authenticated users can upload only into their own folder:
-- folder name = auth.uid().
-- Public read is optional; for a private production service use signed URLs instead.
