-- Run this in Supabase SQL Editor.

-- UPGRADED: Added avatar_url column to profiles table tracking user profile pics
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  avatar_url text not null default 'https://unsplash.com',
  created_at timestamptz not null default now()
);

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  caption text not null default '',
  video_path text not null,
  video_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.likes (
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,video_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  reason text not null,
  created_at timestamptz not null default now()
);

-- NEW FEATURE: Follow relationships ledger architecture mapping
create table if not exists public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(follower_id, following_id)
);

-- NEW FEATURE: WhatsApp style direct messaging ledger record matrix
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  message_text text not null check (char_length(message_text) between 1 and 2000),
  created_at timestamptz not null default now()
);

-- Enable Row Level Security configurations globally
alter table public.profiles enable row level security;
alter table public.videos enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;
alter table public.reports enable row level security;
alter table public.follows enable row level security;
alter table public.messages enable row level security;

-- Profiles security access vectors
create policy "profiles readable" on public.profiles for select using (true);
create policy "own profile insert" on public.profiles for insert with check (auth.uid()=id);
create policy "own profile update" on public.profiles for update using (auth.uid()=id);

-- Videos security access vectors
create policy "videos readable" on public.videos for select using (true);
create policy "own video insert" on public.videos for insert with check (auth.uid()=user_id);
create policy "own video delete" on public.videos for delete using (auth.uid()=user_id);

-- Likes security access vectors
create policy "likes readable" on public.likes for select using (true);
create policy "own like insert" on public.likes for insert with check (auth.uid()=user_id);
create policy "own like delete" on public.likes for delete using (auth.uid()=user_id);

-- Comments security access vectors
create policy "comments readable" on public.comments for select using (true);
create policy "comment insert" on public.comments for insert with check (auth.uid()=user_id);
create policy "own comment delete" on public.comments for delete using (auth.uid()=user_id);

-- Reports security access vectors (Protected, not open to public scanning)
create policy "reports insert" on public.reports for insert with check (auth.uid()=reporter_id);

-- Follows security access vectors
create policy "follows readable" on public.follows for select using (true);
create policy "own follow insert" on public.follows for insert with check (auth.uid()=follower_id);
create policy "own follow delete" on public.follows for delete using (auth.uid()=follower_id);

-- Messaging security access vectors (Ensures users can only read messages sent to/by them)
create policy "messages readable" on public.messages for select using (auth.uid()=sender_id or auth.uid()=receiver_id);
create policy "message insert" on public.messages for insert with check (auth.uid()=sender_id);

-- Storage configuration tracking notes:
-- Create a Storage bucket named "videos" in your Supabase Dashboard interface.
-- Add Storage policies so authenticated users can upload only into their own folders:
-- folder path parameter context mapping rule = auth.uid()
